PublisherAndBook/Controllers/PublishersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PublisherAndBook.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PublisherAndBook.Controllers
{
    public class PublishersController : Controller
    {
        readonly ManageDbContext db;
        public PublishersController(ManageDbContext db)
        {
            this.db = db;
        }
        public IActionResult Index()
        {
            return View(db.Publishers.ToList());
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Publisher publisher)
        {
            if (ModelState.IsValid)
            {
                db.Publishers.Add(publisher);
                db.SaveChanges();
                return PartialView("_CreatePartial", true);
            }
            return PartialView("_CreatePartial", false);
        }
        //Edit
        public IActionResult Edit(int id)
        {
            return View(db.Publishers.First(x => x.PublisherId == id));

        }

        [HttpPost]
        public IActionResult Edit(Publisher p)
        {
            if (ModelState.IsValid)
            {
                db.Entry(p).State = EntityState.Modified;
                db.SaveChanges();
                return PartialView("_EditPartial", true);
            }
            return PartialView("_EditPartial", false);
        }

        public IActionResult Delete(int id)
        {
            return View(db.Publishers.First(x => x.PublisherId == id));
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DoDelete(int id)
        {
            var publisher = new Publisher { PublisherId = id };
            if (!db.Books.Any(x => x.PublisherId == id))
            {
                db.Entry(publisher).State = EntityState.Deleted;
                db.SaveChanges();
                return PartialView("_PDelete", true);
            }
            ModelState.AddModelError("", "Cannot delete. Publisher has related Books.");
            //return View(db.Publishers.First(x => x.PublisherId == id));
            return PartialView("_PDelete", false);

        }
    }
}

PublisherAndBook/Views/Publishers/Create.cshtml
@model Publisher
@{
    ViewData["Title"] = "Create";
}
<div class="row">
    <div class="col-6 offset-2 shadow p-3 mb-5 bg-white rounded">
        <h3>Create Publisher</h3>
        <div id="placeholder"></div>
        <form method="post" asp-action="Create" asp-controller="Publishers" id="fpubliser"
              data-ajax="true"
              data-ajax-method="POST"
              data-ajax-mode="replace"
              data-ajax-update="#placeholder"
              data-ajax-success="onSuccess">
            <div class="form-group row mb-1">
                <label asp-for="PublisherName" class="col-form-label col-form-label-sm col-2"></label>
                <div class="col-6">
                    <input type="text" asp-for="PublisherName" class="form-control form-control-sm" />
                    <span asp-validation-for="PublisherName" class="text-danger" />
                </div>
            </div>
            <div class="form-group row mb-1">
                <label asp-for="Establish" class="col-form-label col-form-label-sm col-2"></label>
                <div class="col-6">
                    <input type="text" asp-for="Establish" class="form-control form-control-sm" />
                    <span asp-validation-for="Establish" class="text-danger" />
                </div>
            </div>
            <div class="form-group row mb-1">

                <div class="col-6 offset-2">
                    <button type="submit" class="btn btn-success">Save</button>
                </div>
            </div>
        </form>
        <div class="row">
            <div class="col-6">
                <a class="btn btn-dark" asp-action="Index" asp-controller="Publishers"><i class="bi bi-layer-backward"></i> Back to Index</a>
            </div>
        </div>
    </div>
</div>
@section styles {
    <link href="~/libs/datepicker/css/bootstrap-datepicker.standalone.css" rel="stylesheet" />
    <link href="~/libs/icons/font/bootstrap-icons.css" rel="stylesheet" />
}
@section scripts {
    <script src="~/libs/jquery/jquery.js"></script>
    <script src="~/libs/jquery/jquery.validate.js"></script>
    <script src="~/libs/jquery/jquery.validate.unobtrusive.js"></script>
    <script src="~/libs/datepicker/js/bootstrap-datepicker.js"></script>
    <script src="~/libs/jquery/ajax/jquery.unobtrusive-ajax.js"></script>
    <script>
        $("#Establish").datepicker({
            format: "M dd, yyyy"
        });
    </script>
    <script>
        function onSuccess() {
            $("#fpubliser").trigger('reset');
        }
    </script>

}

PublisherAndBook/Views/Publishers/Delete.cshtml
@model Publisher
@{
    ViewData["Title"] = "Edit";
}

<div class="row">
    <div class="col-6 offset-2 shadow p-3 mb-5 bg-white rounded">
        <h3>Sure to delete?</h3>
        <div id="placeholder" class="text-danger"></div>
        <div class="row my-1">
            <div asp-validation-summary="All" class="text-danger"></div>
        </div>
        <div class="form-group row mb-1">
            <label asp-for="PublisherName" class="col-form-label col-form-label-sm col-2"></label>
            <div class="col-4">
                <label>@Model.PublisherName</label>

            </div>
        </div>

        <div class="form-group row mb-1">
            <label asp-for="Establish" class="col-form-label col-form-label-sm col-2"></label>
            <div class="col-4">
                <label>@Model.Establish</label>
            </div>
        </div>
        <form method="post" asp-action="Delete" asp-controller="Publishers" asp-route-PublisherId="@Model.PublisherId"
              id="fpubliser"
              data-ajax="true"
              data-ajax-method="POST"
              data-ajax-mode="replace"
              data-ajax-update="#placeholder"
              data-ajax-success="onSuccess">
            <div class="form-group row mb-1">

                <div class="col-4 offset-2">
                    <button type="submit" class="btn btn-danger">Delete</button>
                </div>
            </div>
        </form>
        <div class="row">
            <div class="col-8">
                <a class="btn btn-dark" asp-action="Index" asp-controller="Publishers"><i class="bi bi-layer-backward"></i> Back to Index</a>
            </div>
        </div>
    </div>
</div>
@section styles{
    <link href="~/libs/icons/font/bootstrap-icons.css" rel="stylesheet" />

}

@section scripts {
    <script src="~/libs/jquery/jquery.js"></script>
    <script src="~/libs/jquery/jquery.validate.js"></script>
    <script src="~/libs/jquery/jquery.validate.unobtrusive.js"></script>
    <script src="~/libs/jquery/ajax/jquery.unobtrusive-ajax.js"></script>
    <script>
        function onSuccess() {
            $("#fpubliser").trigger('reset');
        }
    </script>
}

PublisherAndBook/Views/Publishers/Edit.cshtml
@model Publisher
@{
    ViewData["Title"] = "Edit";
}

<div class="row">
    <div class="col-6 offset-2 shadow p-3 mb-5 bg-white rounded">
        <h3>Edit Publisher</h3>
        <div id="placeholder"></div>
        <form method="post" asp-action="Edit" asp-controller="Publishers" asp-route-PublisherId="@Model.PublisherId" id="fpubliser"
              data-ajax="true"
              data-ajax-method="POST"
              data-ajax-mode="replace"
              data-ajax-update="#placeholder"
              data-ajax-success="onSuccess">
            <div class="form-group row mb-1">
                <label asp-for="PublisherName" class="col-form-label col-form-label-sm col-2"></label>
                <div class="col-6">
                    <input type="text" asp-for="PublisherName" class="form-control form-control-sm" />
                    <span asp-validation-for="PublisherName" class="text-danger" />
                </div>
            </div>
            <div class="form-group row mb-1">
                <label asp-for="Establish" class="col-form-label col-form-label-sm col-2"></label>
                <div class="col-6">
                    <input type="text" asp-for="Establish" class="form-control form-control-sm" />
                    <span asp-validation-for="Establish" class="text-danger" />
                </div>
            </div>
            <div class="form-group row mb-1">

                <div class="col-6 offset-2">
                    <button type="submit" class="btn btn-success">Update</button>
                </div>
            </div>
        </form>
        <div class="row">
            <div class="col-6">
                <a class="btn btn-dark" asp-action="Index" asp-controller="Publishers"><i class="bi bi-layer-backward"></i> Back to Index</a>
            </div>
        </div>
    </div>

</div>

@section styles {
    <link href="~/libs/datepicker/css/bootstrap-datepicker.standalone.css" rel="stylesheet" />
    <link href="~/libs/icons/font/bootstrap-icons.css" rel="stylesheet" />
}
@section scripts {
    <script src="~/libs/jquery/jquery.js"></script>
    <script src="~/libs/jquery/jquery.validate.js"></script>
    <script src="~/libs/jquery/jquery.validate.unobtrusive.js"></script>
    <script src="~/libs/datepicker/js/bootstrap-datepicker.js"></script>
    <script src="~/libs/jquery/ajax/jquery.unobtrusive-ajax.js"></script>
    <script>
        $("#Establish").datepicker({
            format: "M dd, yyyy"
        });
    </script>
    <script>
        function onSuccess() {
            $("#fpubliser").trigger('reset');
        }
    </script>
}

PublisherAndBook/Views/Publishers/Index.cshtml
@model IEnumerable<Publisher>
@{
    ViewData["Title"] = "Index";
}
<div class="row">
    <div class="offset-sm-2 col-6 shadow p-3 mb-5 bg-white rounded">
        <div class="d-flex justify-content-end mb-1">
            <div class="col-11 "><h3>Publisher</h3></div>
            <div class="col-1 justify-content-end">
                <a class="btn btn-primary" asp-controller="Publishers" asp-action="Create"><i class="bi bi-plus-lg"></i></a>
            </div>
        </div>
        <table class="table table-hover table-bordered table-striped">
            <thead class="table-light">
                <tr>
                    <th>@Html.DisplayNameFor(x => x.PublisherName)</th>
                    <th>@Html.DisplayNameFor(x => x.Establish)</th>
                    <th style="width:130px" class="text-center">
                        Actions
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var p in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(x => p.PublisherName)</td>
                        <td>@Html.DisplayFor(x => p.Establish)</td>
                        <td class="text-center">
                            <a class="btn btn-success" asp-controller="Publishers" asp-action="Edit" asp-route-id="@p.PublisherId"><i class="bi bi-pencil"></i></a>
                            <a class="btn btn-danger" asp-controller="Publishers" asp-action="Delete" asp-route-id="@p.PublisherId"><i class="bi bi-trash"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@section styles {
    <link href="~/libs/icons/font/bootstrap-icons.css" rel="stylesheet" />
}

PublisherAndBook/Views/Publishers/_CreatePartial.cshtml
@model bool@if (Model){<div class="alert alert-success alert-dismissible fade show" role="alert">    <strong>Success!</strong> Data saved.    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div> }            else            {<div class="alert alert-warning alert-dismissible fade show" role="alert">    <strong>Success!</strong> Operation failed.    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>}

PublisherAndBook/Views/Publishers/_EditPartial.cshtml
@model bool@if (Model){<div class="alert alert-success alert-dismissible fade show" role="alert">    <strong>Success!</strong> Update data.    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div> }else{<div class="alert alert-warning alert-dismissible fade show" role="alert">    <strong>Success!</strong> Operation failed.    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>}

PublisherAndBook/Views/Publishers/_PDelete.cshtml
@model bool?

@if (Model.Value)
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Success!</strong> This Publisher is Deletet.
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
else
{
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>Error!</strong> Cannot delete! Publisher has related Book.
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
}